### ISSUE TITLE
Make binary aware of environment variables

### ISSUE THREAD

**Issue by locks** [ember-learn/tool-new-release#30]
## Tasks
- [ ] Make tool support reading necessary vars from the environment instead of Heroku
- [ ] Use `dotenv` to make local development easier
  - [ ] Create .env.example
  - [ ] Create script to populate .env from Heroku ?

**Comment by locks** [comment]
Fixed by using 1Password.
